collections:
  "151":
    aliases:
      - Pokémon 151
      - Pokemon 151
      - Scarlet & Violet 151
      - SV 151
      - coleção 151
      - set 151

  "Scarlet & Violet":
    aliases:
      - Escarlate e Violeta
      - Scarlet Violet
      - SV
      - S&V

  "Prismatic Evolutions":
    aliases:
      - Evoluções Prismáticas
      - Prismatic
      - Prismatic Evolutions
      - Evoluções Prismaticas

  "Surging Sparks":
    aliases:
      - Faíscas Impetuosas
      - Surging Sparks
      - Sparks

  "Journey Together":
    aliases:
      - Journey Together
      - Jornada Juntos
      - Juntos de Jornada

  "Destined Rivals":
    aliases:
      - Destined Rivals
      - Rivais Destinados

  "Black Bolt":
    aliases:
      - Black Bolt
      - Raio Negro

  "White Flare":
    aliases:
      - White Flare
      - Chama Branca

  "Mega Evolution":
    aliases:
      - Megaevolução
      - Mega Evolução
      - Mega Evolution
      - Mega

  "Heróis Excelsos":
    aliases:
      - Heróis Excelsos
      - Herois Excelsos
      - Mega Evolution Heroes
      - Mega Evolution Heróis Excelsos
      - Megaevolução Heróis Excelsos

  "Escuridão Absoluta":
    aliases:
      - Escuridão Absoluta
      - Escuridao Absoluta
      - Pitch Black
      - Mega Evolution Pitch Black

  "Caos Ascendente":
    aliases:
      - Caos Ascendente
      - Ascending Chaos
      - Mega Evolution Caos Ascendente
