communities:
  - reddit.com
  - discord.com
  - disboard.org

social_public:
  - facebook.com
  - instagram.com
  - tiktok.com
  - youtube.com
  - x.com
  - twitter.com
  - threads.net

marketplaces:
  - mercadolivre.com.br
  - olx.com.br
  - shopee.com.br
  - enjoei.com.br
  - amazon.com.br

tcg_specialized:
  - ligapokemon.com.br
  - mypcards.com
  - bigdex.app
  - droper.app
  - cardsrealm.com
