rarity_terms:
  - SAR
  - SIR
  - AR
  - IR
  - UR
  - SR
  - HR
  - FA
  - Full Art
  - Alt Art
  - Secret Rare
  - Illustration Rare
  - Special Illustration Rare
  - Hyper Rare
  - Ultra Rare
  - Gold
  - Rainbow
  - Promo
  - Stamped
  - Reverse
  - Holo
  - Radiant
  - Amazing Rare
  - Trainer Gallery
  - Galeria de Treinador
