core_terms:
  - Pokémon TCG
  - Pokemon TCG
  - Pokémon Estampas Ilustradas
  - cartas Pokémon
  - carta Pokémon
  - card Pokémon
  - card game
  - Copag

card_type_terms:
  - ex
  - EX
  - V
  - VMAX
  - VSTAR
  - GX
  - Mega
  - Mega Evolution
  - Megaevolução
  - Radiant
  - Shiny
  - Baby Shiny
  - Trainer
  - Supporter
  - Item
  - Stadium

language_terms:
  - português
  - PT-BR
  - pt br
  - nacional
  - Copag
  - inglês
  - english
  - japonês
  - JP
  - japonesa
  - importada
